### PR TITLE
Nix Flake Support

### PR DESCRIPTION
**Pull request by emctoo**

### CODE REVIEW

**Comment by xoolive** [comment]
I had to fix minor things for running on MacOS on my side (still not committed), but now I am stuck here:

```
➜ nix shell
warning: ignoring the client-specified setting 'trusted-public-keys', because it is a restricted setting and you are not a trusted user
warning: ignoring the client-specified setting 'trusted-substituters', because it is a restricted setting and you are not a trusted user
error: builder for '/nix/store/ldgil0yqxxww6cca9r5l5dn1nbvr07kg-jet1090-0.2.5.drv' failed with exit code 101;
       last 25 log lines:
       >  --> crates/rs1090/src/lib.rs:3:10
       >   |
       > 3 | #![doc = include_str!("../readme.md")]
       >   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       >   |
       >   = note: this error originates in the macro `include_str` (in Nightly builds, run with -Z macro-backtrace for more info)
       >
       > error: couldn't read `crates/rs1090/src/data/../../data/airports.json`: No such file or directory (os error 2)
       >   --> crates/rs1090/src/data/airports.rs:29:29
       >    |
       > 29 | const AIRPORTS_JSON: &str = include_str!("../../data/airports.json");
       >    |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       >    |
       >    = note: this error originates in the macro `include_str` (in Nightly builds, run with -Z macro-backtrace for more info)
       >
       > error: couldn't read `crates/rs1090/src/data/../../data/patterns.json`: No such file or directory (os error 2)
       >   --> crates/rs1090/src/data/patterns.rs:29:29
       >    |
       > 29 | const PATTERNS_JSON: &str = include_str!("../../data/patterns.json");
       >    |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       >    |
       >    = note: this error originates in the macro `include_str` (in Nightly builds, run with -Z macro-backtrace for more info)
       >
       > error: could not compile `rs1090` (lib) due to 3 previous errors
       > warning: build failed, waiting for other jobs to finish...
       For full logs, run 'nix log /nix/store/ldgil0yqxxww6cca9r5l5dn1nbvr07kg-jet1090-0.2.5.drv'.
[1]    71359 exit 1     nix shell
```

**Comment by xoolive** [comment]
Maybe it would be nice to also add a GitHub action to confirm things work:
https://github.com/marketplace/actions/install-nix

**Comment by emctoo** [comment]
Yeah, that will be great. And even better if we can have multi-arch binary build with Github CI, my earlier plan. I'm on that. 

I'm sure, but is it even possible to create static build? @xoolive

**Comment by xoolive** [comment]
Yes the builds are made on each release, check the release page. But it would be nice to have the flake version working too.

**Pull request merged**
